"use client";

import Image from 'next/image'; 
import { useState } from "react";

export default function Economics_1() {
  const [selected, setSelected] = useState(null);

  const correctAnswer = "False";

  const handleSelect = (value) => {
    setSelected(value);
  };

  return (
    <div className="font-montserrat">
      <h1 className="text-5xl mt-10"> Economics of Solar Energy</h1>
      <h2 className="text-3xl mt-10 pb-10 font-semibold">3.1 - The Rise of Solar Power</h2>

      {/* content */}
      <div className="flex flex-row gap-8">
          {/* text */}
          <div className="w-150">
              <p className="mb-10">
                  <strong>Fringe to forefront</strong>: In the past 10 years, the manufacturing and deployment of solar energy around the world has increased exponentially. While solar was a fringe technology with niche applications 20 years ago, it is now being implemented at a rate greater than any other energy source. <strong>In 2024 there were 50 gigawatts of solar capacity added to the US energy grid</strong>—the most of any energy source and the largest annual capacity addition in over two decades. (SEIA)
              </p>
              <p className="mb-10">
                  <strong>Fossil fuels</strong>: New capacity for <span className="text-red-500">fossil fuel–based</span> electricity has stagnated. In 2024 there were <strong>2.5 gigawatts</strong> of natural gas capacity added to the grid—the lowest in 25 years—in large part because of solar. (EIA)
              </p>
              <p className="mb-10">
                  <strong>Big picture</strong>: Despite solar’s momentum, it still makes up <strong>less than 5%</strong> of total electricity generation in the US, while coal and natural gas together account for over <strong>50%</strong>. There’s still a long way to decarbonize the US electricity grid. (EIA)
              </p>
          </div>

          {/* graphic */}
          <div className="flex flex-col">
            <Image
              src="/enviornmental/solar_energy_growth.png"
              alt="Solar energy growth"
              width={1240}
              height={840}
              className="w-[450px] h-auto" // controls size, keeps proportions
            />

            {/* quiz */}
            <div className="flex mt-5 flex-col items-start w-full max-w-xl mx-auto">
              <div className="mt-4 text-lg font-medium">
                The majority of electricity in the US is now generated by solar
              </div>

              <div className="mt-3 space-y-2">
                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="answer"
                    value="True"
                    checked={selected === "True"}
                    onChange={() => handleSelect("True")}
                    className="accent-blue-500"
                  />
                  True
                </label>

                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="answer"
                    value="False"
                    checked={selected === "False"}
                    onChange={() => handleSelect("False")}
                    className="accent-blue-500"
                  />
                  False
                </label>
              </div>

              {selected && (
                <div className="mt-3 text-sm font-semibold">
                  {selected === correctAnswer
                    ? "✅ Correct"
                    : "❌ Incorrect"}
                </div>
              )}
            </div>
          </div>
      </div>
    </div>
  );
}

