"use client";

import Image from 'next/image'; 
import { useState } from "react";

export default function Environmental_1() {
  const [selected, setSelected] = useState(null);

  const correctAnswer = "False";

  const handleSelect = (value) => {
    setSelected(value);
  };

  return (
    <div className="font-montserrat">
      <h1 className="text-5xl mt-10"> Environmental Sustainability of Solar Energy</h1>
      <h2 className="text-3xl mt-10 pb-10 font-semibold">1.1 - The Rise of Solar Panel</h2>

      {/* content */}
      <div className="flex flex-row gap-8">
          {/* text */}
          <div className="w-150">
              <p className="mb-10">
                  <strong>Fringe to forefront</strong>: In the past 10 years the manufacturing and deployment 
                  of solar has energy around the world has increased exponentially. While 
                  solar only Solar was a fringe technology with niche applications 20 years ago 
                  but is now being implemented at a rate greater than any other energy  
                  source. <strong>In 2024 there was 50 gigawatts of solar capacity added to the US 
                  energy grid, the most out of any energy source</strong>, and the most capacity 
                  added by one energy source in a year in over two decades.  
                  <a className="text-blue-500 underline"
                      href="https://seia.org/news/report-solar-adds-more-new-capacity-to-the-grid-in-2024-than-any-energy-technology-in-the-past-two-decades/#:~:text=Past%20Two%20Decades-,WASHINGTON%2C%20D.C.,technology%20in%20over%20two%20decades.">
                      (SEIA)
                  </a>
              </p>
              <p className="mb-10">
                  <strong>Fossile fuels</strong>:  On the other hand, new capacity for <span className="text-red-500">fossil fuel based electricity
                  generation has stagnated</span>. In 2024 there was 2.5 gigawatts of natural gas 
                  capacity added to the grid, the lowest in 25 years, in large part because of
                  the solar. 
                  <a className="text-blue-500 underline"
                      href="https://www.eia.gov/todayinenergy/detail.php?id=64126#:~:text=Wind.,end%20of%20July%20last%20year.">
                      (EIA)
                  </a>
              </p>
              <p className="mb-10">
                  <strong>Big picture</strong>: Despite solar’s current momentum, it still just makes up <strong>less 
                  than 5%</strong> of total electricity generation in the US, while coal and natural gas 
                  make up over 50%. So while solar’s current momentum is exciting, there is a 
                  long way to go to decarbonize the US electricity grid.
                  <a className="text-blue-500 underline"
                      href="https://www.eia.gov/outlooks/steo/report/BTL/2023/02-genmix/article.php">
                      (EIA)
                  </a>
              </p>
          </div>

          {/* graphic */}
          <div className="flex flex-col">
            <Image
              src="/enviornmental/solar_energy_growth.png"
              alt="Solar energy growth"
              width={1240}
              height={840}
              className="w-[450px] h-auto" // controls size, keeps proportions
            />

            {/* quiz */}
            <div className="flex mt-5 flex-col items-start w-full max-w-xl mx-auto">
              <div className="mt-4 text-lg font-medium">
                The majority of electricity in the US is now generated by solar
              </div>

              <div className="mt-3 space-y-2">
                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="answer"
                    value="True"
                    checked={selected === "True"}
                    onChange={() => handleSelect("True")}
                    className="accent-blue-500"
                  />
                  True
                </label>

                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="answer"
                    value="False"
                    checked={selected === "False"}
                    onChange={() => handleSelect("False")}
                    className="accent-blue-500"
                  />
                  False
                </label>
              </div>

              {selected && (
                <div className="mt-3 text-sm font-semibold">
                  {selected === correctAnswer
                    ? "✅ Correct"
                    : "❌ Incorrect"}
                </div>
              )}
            </div>
          </div>
      </div>
    </div>
  );
}