"use client";

import Image from 'next/image'; 
import { useState } from "react";

export default function Environmental_1() {
  const [selected, setSelected] = useState(null);

  const correctAnswer = "True";

  const handleSelect = (value) => {
    setSelected(value);
  };

  return (
    <div className="font-montserrat">
      <h1 className="text-5xl mt-10"> Environmental Sustainability of Solar Energy</h1>
      <h2 className="text-3xl mt-10 pb-10 font-semibold">1.2 - What is Sustainability?</h2>

      {/* content */}
      <div className="flex flex-row gap-8">
          {/* text */}
          <div className="w-150">
              <p className="mb-10">
                  <strong>Planet Blue Definition</strong>: Sustainability is a mindset and 
                  framework for ensuring that current and future generations have equitable
                   access to the resources for a full and vibrant life without the exploitation
                    of people, society, or the environment. 
                  <a className="text-blue-500 underline"
                      href="https://planetblue.umich.edu/campus/about/">
                      (Planet Blue)
                  </a>
              </p>
              <p className="mb-10">
                  <strong>The Triple Bottom Line (TBL)</strong>: is a framework that evaluates
                   an organization's performance based on three dimensions: social, environmental, 
                   and financial outcomes. It emphasizes that businesses should focus not 
                   only on profit (the traditional "bottom line") but also on their impact 
                   on people and the planet. 
                  <a className="text-blue-500 underline"
                      href="https://online.hbs.edu/blog/post/what-is-the-triple-bottom-line">
                      (Harvard Business School)
                  </a>
              </p>
              <p className="mb-10">
                  <strong>Three Pillars of TBL</strong>: While solar energy supports all 
                    three pillars of the TBL, this crash course will focus primarily on the
                    third pillar, environmental sustainability, and how solar energy is one
                    of most important solutions that we have in the face of worsening climate change
              </p>
          </div>

          {/* graphic */}
          <div className="flex flex-col">
            <Image
              src="/enviornmental/solar_energy_growth.png"
              alt="Solar energy growth"
              width={1240}
              height={840}
              className="w-[450px] h-auto" // controls size, keeps proportions
            />

            {/* quiz */}
            <div className="flex mt-5 flex-col items-start w-full max-w-xl mx-auto">
              <div className="mt-4 text-lg font-medium">
                The majority of electricity in the US is now generated by solar
              </div>

              <div className="mt-3 space-y-2">
                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="answer"
                    value="True"
                    checked={selected === "True"}
                    onChange={() => handleSelect("True")}
                    className="accent-blue-500"
                  />
                  True
                </label>

                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="answer"
                    value="False"
                    checked={selected === "False"}
                    onChange={() => handleSelect("False")}
                    className="accent-blue-500"
                  />
                  False
                </label>
              </div>

              {selected && (
                <div className="mt-3 text-sm font-semibold">
                  {selected === correctAnswer
                    ? "✅ Correct"
                    : "❌ Incorrect"}
                </div>
              )}
            </div>
          </div>
      </div>
    </div>
  );
}