"use client";

import Image from 'next/image'; 
import { useState } from "react";

export default function Environmental_1() {
  const [selected, setSelected] = useState(null);

  const correctAnswer = "False";

  const handleSelect = (value) => {
    setSelected(value);
  };

  return (
    <div className="font-montserrat">
      <h1 className="text-5xl mt-10"> Environmental Sustainability of Solar Energy</h1>
      <h2 className="text-3xl mt-10 pb-10 font-semibold">1.3 - What Makes Solar Energy Sustainable?</h2>

      {/* content */}
      <div className="flex flex-row gap-8">
          {/* text */}
          <div className="w-150">
              <p className="mb-10">
                  <strong>Solar is renewable:</strong>: Solar energy generation is a form of 
                  <span className="text-red-500 font-bold"> renewable energy,</span> meaning 
                  that it is drawing on a source of energy that is virtually inexhaustible, 
                  as the sun will continue to shine for billions of years. The Earth continuously 
                  receives <span className="text-red-500 font-bold"> more than 10,000 times </span>
                  its total energy usage in the form of solar radiation <a className="text-blue-500 underline"
                      href="https://www.nasa.gov/wp-content/uploads/2015/03/135642main_balance_trifold21.pdf?emrc=5b9a71#:~:text=The%20Sun%20is%20the%20major,will%20lose%20energy%20to%20space.">
                    (NASA)
                  </a>, and we can tap into this unlimited resource!
              </p>
              <p className="mb-10">
                  <strong>Fossil fuels are finite:</strong>: On the other hand, <span className="text-red-500 font-bold">fossil fuels</span>, 
                  which continue to make up the majority of energy generation in the US, 
                  burn fuels mined and drilled from the ground, a practice that physically 
                  cannot continue for centuries as reserves will <a className="text-blue-500 underline"
                      href="https://www.fairplanet.org/story/when-will-we-run-out-of-fossil-fuels/">
                      run out
                  </a>.
              </p>
              <p className="mb-10">
                  <strong>Environmental impact:</strong>: Additionally, fossil fuels damage 
                  ecosystems through air and water pollution, habitat destruction from 
                  extraction, and greenhouse gas emissions that drive climate change—making 
                  solar a cleaner alternative for long-term sustainability.
              </p>
          </div>

          {/* graphic */}
          <div className="flex flex-col">
            <Image
              src="/enviornmental/solar_energy_growth.png"
              alt="Solar energy growth"
              width={1240}
              height={840}
              className="w-[450px] h-auto" // controls size, keeps proportions
            />

            {/* quiz */}
            <div className="flex mt-5 flex-col items-start w-full max-w-xl mx-auto">
              <div className="mt-4 text-lg font-medium">
                The majority of electricity in the US is now generated by solar
              </div>

              <div className="mt-3 space-y-2">
                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="answer"
                    value="True"
                    checked={selected === "True"}
                    onChange={() => handleSelect("True")}
                    className="accent-blue-500"
                  />
                  True
                </label>

                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="answer"
                    value="False"
                    checked={selected === "False"}
                    onChange={() => handleSelect("False")}
                    className="accent-blue-500"
                  />
                  False
                </label>
              </div>

              {selected && (
                <div className="mt-3 text-sm font-semibold">
                  {selected === correctAnswer
                    ? "✅ Correct"
                    : "❌ Incorrect"}
                </div>
              )}
            </div>
          </div>
      </div>
    </div>
  );
}